#!/bin/bash
NAME="Djangoredes"
VIRTUALENV="/home/ricardo/Django/Redes/.venv/"
DJANGODIR="/home/ricardo/Django/Redes/Djangoredes/"
USER=ricardo
GROUP=sudo
NUM_WORKERS=5
DJANGO_WSGI_MODULE=APPREDES.wsgi

echo "Starting $NAME as `whoami`"

cd $VIRTUALENV
. bin/activate
cd $DJANGODIR

export PYTHONPATH=$DJANGODIR:$PYTHONPATH

exec gunicorn ${DJANGO_WSGI_MODULE} \
        --workers $NUM_WORKERS \
        --user=$USER --group=$GROUP \
        --log-level=debug \
        --bind=127.0.0.1:8000

